/**
 * CSS custom properties formatter.
 *
 * Converts a TokenDocument to one or more CSS files containing `:root { ... }`
 * (and optionally per-mode selectors like `.dark { ... }`). The first
 * "real" non-DTCG output, completing the canonical-to-runtime pipeline.
 *
 * Behavior:
 *   - Each token becomes a CSS custom property. Path joined with `-`,
 *     optionally prefixed. `color/primary` → `--color-primary`.
 *   - Aliases resolve to `var(--target-token)` so CSS cascading still works.
 *   - Composite tokens (typography, shadow) expand into multiple primitive
 *     custom properties since CSS doesn't natively express composites.
 *   - Single-mode tokens go in `:root`.
 *   - Multi-mode tokens emit per-mode selectors. Heuristic: a mode named
 *     `Light`/`Default` becomes `:root`; `Dark` becomes `.dark` (Tailwind
 *     convention); other modes become `[data-theme="<name>"]`.
 *   - splitByMode emits one file per mode with just that mode's values.
 *   - splitByCollection emits one file per set.
 */

import type { Token, TokenDocument, TokenSet, TokenValue } from "../types.js";
import type { FormatOptions, FormatResult } from "./index.js";

export function formatCssVars(
  doc: TokenDocument,
  opts: FormatOptions,
): FormatResult {
  const warnings: string[] = [];
  const files: FormatResult["files"] = [];

  const splitByMode = opts.target.splitByMode ?? false;
  const splitByCollection = opts.target.splitByCollection ?? false;
  const prefix = opts.target.prefix ?? "";

  if (splitByMode && splitByCollection) {
    // One file per (set, mode) pair.
    for (const set of doc.sets) {
      for (const mode of set.modes) {
        files.push({
          path: filenameFor(opts, set, mode),
          content: renderSingleSelector(
            doc.sets.filter((s) => s.name === set.name),
            mode,
            selectorFor(mode),
            prefix,
            warnings,
          ),
        });
      }
    }
  } else if (splitByMode) {
    // One file per mode, all sets combined under that mode's selector.
    const allModes = new Set<string>();
    for (const set of doc.sets) for (const m of set.modes) allModes.add(m);
    for (const mode of allModes) {
      const setsWithMode = doc.sets.filter((s) => s.modes.includes(mode));
      files.push({
        path: filenameFor(opts, undefined, mode),
        content: renderSingleSelector(
          setsWithMode,
          mode,
          selectorFor(mode),
          prefix,
          warnings,
        ),
      });
    }
  } else if (splitByCollection) {
    // One file per set, all modes combined as separate selectors within.
    for (const set of doc.sets) {
      files.push({
        path: filenameFor(opts, set),
        content: renderMultiSelector([set], prefix, warnings),
      });
    }
  } else {
    // Single file with everything.
    files.push({
      path: filenameFor(opts),
      content: renderMultiSelector(doc.sets, prefix, warnings),
    });
  }

  return { files, warnings };
}

function filenameFor(
  opts: FormatOptions,
  set?: TokenSet,
  mode?: string,
): string {
  if (opts.target.filename) return opts.target.filename;
  const parts: string[] = [];
  if (set) parts.push(slugify(set.name));
  if (mode) parts.push(slugify(mode));
  if (parts.length === 0) parts.push("tokens");
  return `${parts.join(".")}.css`;
}

function slugify(s: string): string {
  return s
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/**
 * Map a mode name to a CSS selector. Conventional defaults that match what
 * most CSS frameworks expect:
 *   - Default / Light / Value → `:root` (the document root, runs always)
 *   - Dark → `.dark` (matches Tailwind's darkMode: "class" config)
 *   - anything else → `[data-theme="<name>"]` (general escape hatch)
 */
function selectorFor(mode: string): string {
  const lower = mode.toLowerCase();
  if (lower === "default" || lower === "light" || lower === "value") {
    return ":root";
  }
  if (lower === "dark") {
    return ".dark";
  }
  return `[data-theme="${slugify(mode)}"]`;
}

/**
 * Render all tokens across the given sets under a single selector. Used when
 * one file holds one mode's worth of vars (splitByMode output).
 */
function renderSingleSelector(
  sets: TokenSet[],
  mode: string,
  selector: string,
  prefix: string,
  warnings: string[],
): string {
  const lines: string[] = [];
  lines.push(`/* Generated by figma-console-mcp — do not edit by hand */`);
  lines.push(`${selector} {`);
  for (const set of sets) {
    for (const token of set.tokens) {
      const value = token.values[mode];
      if (!value) continue;
      emitTokenLines(token, value, prefix, lines, warnings);
    }
  }
  lines.push(`}`);
  lines.push("");
  return lines.join("\n");
}

/**
 * Render multiple sets across multiple modes in one file. Each mode gets its
 * own selector block.
 */
function renderMultiSelector(
  sets: TokenSet[],
  prefix: string,
  warnings: string[],
): string {
  const lines: string[] = [];
  lines.push(`/* Generated by figma-console-mcp — do not edit by hand */`);

  // Collect all (mode, selector) pairs across all sets.
  const modeToSelector = new Map<string, string>();
  for (const set of sets) {
    for (const mode of set.modes) {
      if (!modeToSelector.has(mode)) {
        modeToSelector.set(mode, selectorFor(mode));
      }
    }
  }

  for (const [mode, selector] of modeToSelector) {
    lines.push(`${selector} {`);
    for (const set of sets) {
      if (!set.modes.includes(mode)) continue;
      for (const token of set.tokens) {
        const value = token.values[mode];
        if (!value) continue;
        emitTokenLines(token, value, prefix, lines, warnings);
      }
    }
    lines.push(`}`);
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Emit one or more CSS custom property declarations for a single token.
 * Primitives emit one line; composite tokens (typography, shadow) expand
 * into multiple lines.
 */
function emitTokenLines(
  token: Token,
  value: TokenValue,
  prefix: string,
  out: string[],
  warnings: string[],
): void {
  const cssName = `--${prefix}${token.path.join("-")}`;

  if (value.reference) {
    // Alias → var(--other) so CSS cascading semantics are preserved.
    const targetPath = value.reference.replace(/^\{|\}$/g, "").replace(/\./g, "-");
    out.push(`  ${cssName}: var(--${prefix}${targetPath});`);
    return;
  }

  if (value.literal === undefined || value.literal === null) {
    warnings.push(
      `Token ${token.path.join(".")} has no value — emitting nothing.`,
    );
    return;
  }

  // Composite tokens — expand into multiple primitive vars.
  if (token.type === "typography" && typeof value.literal === "object") {
    const t = value.literal as Record<string, unknown>;
    for (const subField of ["fontFamily", "fontSize", "fontWeight", "lineHeight", "letterSpacing"]) {
      if (t[subField] !== undefined) {
        out.push(`  ${cssName}-${kebab(subField)}: ${formatCssValue(t[subField], token.type)};`);
      }
    }
    return;
  }
  if (token.type === "shadow" && typeof value.literal === "object") {
    const shadowCss = renderShadow(value.literal);
    if (shadowCss) {
      out.push(`  ${cssName}: ${shadowCss};`);
    } else {
      warnings.push(`Token ${token.path.join(".")} has an unparseable shadow value — skipping.`);
    }
    return;
  }

  // Primitives.
  out.push(`  ${cssName}: ${formatCssValue(value.literal, token.type)};`);
}

function kebab(s: string): string {
  return s.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase();
}

/**
 * Render a primitive value as a CSS literal. Numbers gain a "px" suffix when
 * the token type is `dimension`. Strings pass through as-is (assumed to be
 * pre-formatted hex/oklch/rgba etc.).
 */
function formatCssValue(value: unknown, type: string): string {
  if (typeof value === "number") {
    if (type === "dimension") return `${value}px`;
    return String(value);
  }
  if (typeof value === "string") return value;
  if (typeof value === "boolean") return String(value);
  return JSON.stringify(value);
}

function renderShadow(shadow: unknown): string | null {
  if (Array.isArray(shadow)) {
    return shadow
      .map((s) => renderShadow(s))
      .filter(Boolean)
      .join(", ");
  }
  if (!shadow || typeof shadow !== "object") return null;
  const s = shadow as Record<string, unknown>;
  const inset = s.inset ? "inset " : "";
  const x = withPx(s.offsetX);
  const y = withPx(s.offsetY);
  const blur = withPx(s.blur);
  const spread = s.spread !== undefined ? ` ${withPx(s.spread)}` : "";
  const color = s.color;
  if (!x || !y || !blur || typeof color !== "string") return null;
  return `${inset}${x} ${y} ${blur}${spread} ${color}`;
}

function withPx(v: unknown): string {
  if (typeof v === "number") return `${v}px`;
  if (typeof v === "string") return v;
  return "";
}
